#define LIGHTPROBE_GRID_W 16
#define LIGHTPROBE_GRID_H 16
#define LIGHTPROBE_GRID_D 4
#define LIGHTMAP_LAYOUT_W (16*2)
#define LIGHTMAP_LAYOUT_H (16*2)

#define LIGHTPROBE_COLOR_RESOLUTION 6
#define LIGHTPROBE_DEPTH_RESOLUTION 16

#define LIGHTPROBE_CASTS_PER_FRAME 32

#define LIGHTPROBE_SPACING 2.0

#define LIGHTPROBE_OFFSET vec3((-0.5*LIGHTPROBE_GRID_W+0.5)*LIGHTPROBE_SPACING, (-0.5*LIGHTPROBE_GRID_H+0.5)*LIGHTPROBE_SPACING, (-1.0+0.5)*LIGHTPROBE_SPACING)

//derived constants:
#define LIGHTPROBE_COLOR_PADDED_RESOLUTION (LIGHTPROBE_COLOR_RESOLUTION+2)
#define LIGHTMAP_COLOR_TEXTURE_RESOLUTION_UNPADDED (LIGHTPROBE_COLOR_RESOLUTION*LIGHTMAP_LAYOUT_W)
#define LIGHTMAP_COLOR_TEXTURE_RESOLUTION (LIGHTPROBE_COLOR_PADDED_RESOLUTION*LIGHTMAP_LAYOUT_W)
#define LIGHTPROBE_DEPTH_PADDED_RESOLUTION (LIGHTPROBE_DEPTH_RESOLUTION+2)
#define LIGHTMAP_DEPTH_TEXTURE_RESOLUTION_UNPADDED (LIGHTPROBE_DEPTH_RESOLUTION*LIGHTMAP_LAYOUT_W)
#define LIGHTMAP_DEPTH_TEXTURE_RESOLUTION (LIGHTPROBE_DEPTH_PADDED_RESOLUTION*LIGHTMAP_LAYOUT_W)

#define N_LIGHTPROBES (LIGHTPROBE_GRID_W*LIGHTPROBE_GRID_H*LIGHTPROBE_GRID_D)

#define LIGHTMAP_CAST_LOCAL_SIZE LIGHTPROBE_CASTS_PER_FRAME
#define LIGHTMAP_CAST_DISPATCH_W LIGHTMAP_LAYOUT_W
#define LIGHTMAP_CAST_DISPATCH_H LIGHTMAP_LAYOUT_H
#define LIGHTMAP_CAST_DISPATCH_D 1

#define LIGHTMAP_ACCUMULATE_COLOR_DISPATCH_W (LIGHTMAP_LAYOUT_W)
#define LIGHTMAP_ACCUMULATE_COLOR_DISPATCH_H (LIGHTMAP_LAYOUT_H)
#define LIGHTMAP_ACCUMULATE_COLOR_LOCAL_W (LIGHTPROBE_COLOR_RESOLUTION)
#define LIGHTMAP_ACCUMULATE_COLOR_LOCAL_H (LIGHTPROBE_COLOR_RESOLUTION)
#define LIGHTMAP_ACCUMULATE_DEPTH_DISPATCH_W (LIGHTMAP_LAYOUT_W)
#define LIGHTMAP_ACCUMULATE_DEPTH_DISPATCH_H (LIGHTMAP_LAYOUT_H)
#define LIGHTMAP_ACCUMULATE_DEPTH_LOCAL_W (LIGHTPROBE_DEPTH_RESOLUTION)
#define LIGHTMAP_ACCUMULATE_DEPTH_LOCAL_H (LIGHTPROBE_DEPTH_RESOLUTION)
